import axios from 'axios'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'

import PokemonCard from '../../components/pokemonCard'
import { For } from '../../components/utils/for'
import { If } from '../../components/utils/if'
import useDebounce from '../../hooks/use-debounce'
import { Pokemon } from '../../lib/pokemon/schemas'

import type { GetServerSideProps, NextPage } from 'next'
// export const getServerSideProps: GetServerSideProps = async () => {
//   const allOriginPokemons = await getOrigins()

//   const listOfPokemons = await Promise.all(allOriginPokemons.map((pokemon) => getPokemon(pokemon.name)))

//   return {
//     props: {
//       pokemons: listOfPokemons,
//     },
//   }
// }

const Home: NextPage = ({}) => {
  const [pokemons, setPokemons] = useState<Pokemon[]>([])
  const [inputValue, setInputValue] = useState('')
  const [isLoading, setIsLoading] = useState(false)

  useEffect(() => {
    const fetchData = async () => {
      setIsLoading(true)
      const response = await axios.get('/api/pokemon/all')
      setPokemons(response.data as Pokemon[])
      setIsLoading(false)
    }

    fetchData()
  }, [])

  const debouncedValue = useDebounce(inputValue, 500)
  let filteredPokemons = pokemons

  if (debouncedValue) {
    filteredPokemons = pokemons.filter((pokemon) => pokemon.name.toLowerCase().includes(inputValue.toLowerCase()))
  }

  return (
    <div className=" bg-gray-800 min-h-screen p-4 flex flex-col gap-4">
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input className="h-12 text-2xl px-4" value={inputValue} onChange={(e) => setInputValue(e.target.value)} />
      <section className="grid grid-cols-3 2xl:grid-cols-4 gap-4">
        <If isTrue={isLoading}>
          <div>Loading...</div>
        </If>
        <For
          each={filteredPokemons}
          render={(pokemon) => (
            <Link key={pokemon.id} href={`/pokemon/${pokemon.name}`}>
              <a>
                <PokemonCard key={pokemon.id} pokemon={pokemon} />
              </a>
            </Link>
          )}
        />
      </section>
    </div>
  )
}

export default Home
