import Head from 'next/head'
import Link from 'next/link'

import PokemonCard from '../components/pokemonCard'
import { For } from '../components/utils/for'
import { getOrigins, getPokemon } from '../lib/pokemon'
import { Pokemon } from '../lib/pokemon/schemas'

import type { GetStaticProps, NextPage } from 'next'
export const getStaticProps: GetStaticProps = async () => {
  const allOriginPokemons = await getOrigins()

  const listOfPokemons = await Promise.all(allOriginPokemons.map((pokemon) => getPokemon(pokemon.name)))

  return {
    props: {
      pokemons: listOfPokemons,
    },
  }
}

const Home: NextPage<{ pokemons: Pokemon[] }> = ({ pokemons }) => {
  return (
    <div className=" bg-gray-800 p-4">
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="grid grid-cols-3 2xl:grid-cols-4 gap-4">
        <For
          each={pokemons}
          render={(pokemon) => (
            <Link key={pokemon.id} href={`/pokemon/${pokemon.name}`}>
              <a>
                <PokemonCard key={pokemon.id} pokemon={pokemon} />
              </a>
            </Link>
          )}
        />
      </section>
    </div>
  )
}

export default Home
